### ISSUE TITLE
[Feature request] : Function that would return Base64 of QR

### ISSUE THREAD

**Issue by howdyhyber** [ushelp/EasyQRCodeJS#13]
Greetings!

As i use the library, i found something in logs, showing base64 link of qr, and that is what i absolutely need.

Is it possible to have a function returning base64 link of qr?
![qr_base64](https://user-images.githubusercontent.com/22556130/79709157-ffe3bb80-82f3-11ea-8ec4-bf09a3e2e353.png)

**Comment by ushelp** [comment]
https://github.com/ushelp/EasyQRCodeJS-NodeJS#methods

**Comment by ushelp** [comment]
upgrade to 3.6.0+. you can use `onRenderingEnd(qrCodeOptions, base64DataURL)` option to get base64 data when the rendering ends.
```
onRenderingEnd:function(options, dataURL){
    console.info(dataURL);
}
```
