### ISSUE TITLE
Option to remove tooltip on QR

### ISSUE THREAD

**Issue by howdyhyber** [ushelp/EasyQRCodeJS#14]
Is it possible to remove the tooltip of QR? Whenever i hover the QR, it shows up, which i dont need it to.
![screenshot](https://user-images.githubusercontent.com/22556130/79944989-796bdd00-849f-11ea-9bf3-e9ea8c216bde.png)

**Comment by ushelp** [comment]
I add the tooltip option to control it for u. please upgrade to the latest version 3.6.0.
/*
tooltip: false
*/
