### ISSUE TITLE
How to change color of dots?

### ISSUE THREAD

**Issue by Aibaend** [ushelp/EasyQRCodeJS#15]
I use this config   
{
            width: 240,
            height: 240,
            colorDark: "#982844",

            PO: '#982844',
            PI: '#982844',

            correctLevel: QRCode.CorrectLevel.H, // L, M, Q, H

             backgroundImage: 'logo1.png',
            // backgroundImage: 'data:image/png;
            backgroundImageAlpha: 0.3,
            autoColor: true,

            dotScale: 0.5
}

but dots doesn't change into color  "#982844"

**Comment by ushelp** [comment]
![图片](https://user-images.githubusercontent.com/4082017/80959340-3adc0800-8e39-11ea-85a0-c3e382dd3906.png)

please check your code.
