### ISSUE TITLE
Resize function

### ISSUE THREAD

**Issue by raldone01** [ushelp/EasyQRCodeJS#16]
It would be nice if the QRCode had a resize function. Currently I must recreate it everytime the page is resized!
Additionally what is the difference between clear and remove?
Very cool and easy to use library! Thanks!

**Comment by ushelp** [comment]
1. EasyQRCode use Canvas to draw image, vector graphics are not supported. but now you can use the resize method to adjust the size. (v3.6.0+) 
```
qrcode.resize(480, 480); // Resize the image 
```
2. QRCode only support clear method to clear QRCode div
