### ISSUE TITLE
How to save a QR code with nodejs?

### ISSUE THREAD

**Issue by Follow-er** [ushelp/EasyQRCodeJS#2]
I am trying to use this repo to generate a QR code and then save it into a file by the `Node`, but I am not sure how to do it? it seems like I should provide a `DOM_object` as the first argument, so could you please give some idea, thanks!

**Comment by ushelp** [comment]
Hey, @Follow-er, The current image needs to be displayed in the DOM. If you use electron, nw.js, etc., you can save the image through node after rendering.
But we will be releasing new version in the next release, to support Generate QRCode without DOM in Node. That is more suitable for you.

**Comment by Follow-er** [comment]
@ushelp Okay, I see, thanks for your replying!

**Comment by ushelp** [comment]
@Follow-er We have already released a NodeJS qrcode generator project, hope can help u.
Refrenece: 
https://github.com/ushelp/EasyQRCodeJS-NodeJS

**Comment by Skyge** [comment]
@ushelp Thanks, I have tried it and it worked fine, well done!

**Comment by Follow-er** [comment]
@ushelp Thanks, I have tried it and it worked fine, awesome!
