### ISSUE TITLE
canvas 跨域问题 Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by vok123** [ushelp/EasyQRCodeJS#20]
将EasyQRCodeJS 放置CDN, 会出现这样的情况

**Comment by ushelp** [comment]
@vok123 
Canvas toDataURL function does not allow load cross domain image. 
1. Put your image under the same domain, or open CORS
2. Use base64 image(EasyQRCodeJS support)

**Comment by vok123** [comment]
Thanks

**Comment by preservance717** [comment]
i have also same problem. how do you solve this problem?
i have used base64 image, but i don't know config cors.

**Comment by ushelp** [comment]
@preservance717 
If you used base64 image, you do not need to config CORS.

**Comment by ushelp** [comment]
@vok123 

Now please upgrade to latest version 4.3.1. 

Add `crossOrigin` option:

```JS
var options = {
   //...
     crossOrigin: 'anonymous', 
  //...
}
```

**Comment by ushelp** [comment]
https://github.com/ushelp/EasyQRCodeJS#q1-tainted-canvases-may-not-be-exported
