### ISSUE TITLE
Is there an example for Nextjs?

### ISSUE THREAD

**Issue by armspkt** [ushelp/EasyQRCodeJS#21]
Nextjs is a ssr framework but this lib tries to access `DOM` in the server-side.

**Comment by ushelp** [comment]
@armspkt 
you can try ues https://github.com/ushelp/EasyQRCodeJS-NodeJS

**Comment by armspkt** [comment]
> @armspkt 
> 
> you can try ues https://github.com/ushelp/EasyQRCodeJS-NodeJS 

I tried this one already but it did not work too.

**Comment by ushelp** [comment]
@armspkt 
Example:

```JS
import Layout from '../components/Layout';
import Head from "next/head";


class About extends React.Component {
  constructor(props) {
    super(props);
    
    this.qrcodeDOM = React.createRef();
    this.qrcode=null;
  }
  
  generate(color){
      if(this.qrcode){
          this.qrcode.clear();
      }
      var options = {
          text: "https://github.com/ushelp/EasyQRCodeJS",
          colorDark : color?color:'#000000'
      };
      this.qrcode=new QRCode(this.qrcodeDOM.current, options);
  }

  componentDidMount() { 
       this.generate()
  }
  
  render() {
    return (
      <Layout>
          <p>This is About page</p>
          <div ref={this.qrcodeDOM}></div>
          <button onClick={this.generate.bind(this, '#ff0000')}>QRCode Generate</button>
          <Head>
           <script type="text/javascript" src="/static/easy.qrcode.min.js"></script>
         </Head>
           <p>This is About page</p>
      </Layout>
    );
  }
}

export default About;
```

**Comment by armspkt** [comment]
> @armspkt
> Example:
> 
> ```js
> import Layout from '../components/Layout';
> import Head from "next/head";
> 
> 
> class About extends React.Component {
>   constructor(props) {
>     super(props);
>     
>     this.qrcodeDOM = React.createRef();
>     this.qrcode=null;
>   }
>   
>   generate(color){
>       if(this.qrcode){
>           this.qrcode.clear();
>       }
>       var options = {
>           text: "https://github.com/ushelp/EasyQRCodeJS",
>           colorDark : color?color:'#000000'
>       };
>       this.qrcode=new QRCode(this.qrcodeDOM.current, options);
>   }
> 
>   componentDidMount() { 
>        this.generate()
>   }
>   
>   render() {
>     return (
>       <Layout>
>           <p>This is About page</p>
>           <div ref={this.qrcodeDOM}></div>
>           <button onClick={this.generate.bind(this, '#ff0000')}>QRCode Generate</button>
>           <Head>
>            <script type="text/javascript" src="/static/easy.qrcode.min.js"></script>
>          </Head>
>            <p>This is About page</p>
>       </Layout>
>     );
>   }
> }
> 
> export default About;
> ```

it works.


But when I use `import * as QRCode from 'easyqrcodejs';` , it does not work for server-side-rendering.

**Comment by ushelp** [comment]
@armspkt 
server-side-rendering does not support dom operation. please use on client.

**Comment by armspkt** [comment]
> @armspkt
> server-side-rendering does not support dom operation. please use on client.

Ok, thanks
