### ISSUE TITLE
Handling of byte hex string

### ISSUE THREAD

**Issue by ldlamarc** [ushelp/EasyQRCodeJS#22]
When I give "\x00\x00\x01\x01\x65\xba\xcb\x59" as input I would expect it to generate a QR code which outputs 0000010165bacb59 as Binary(HEX) (on a reader that supports binary qr codes. e.g. QRefine on iOs).

Got: EFBBBF0000010165C2BAC38B59

Changing line 74 to: this.parsedData.push(code) seems to fix it so I assume it is related to the utf-8 transforms.

**Comment by ushelp** [comment]
@ldlamarc 
Can your provide some more detail or scene, or an example I can run?
I will try to implement it.

**Comment by ldlamarc** [comment]
See previous comment, not sure if I can add more detail. In summary/spec:

Input: "\x00\x00\x01\x01\x65\xba\xcb\x59"
Current Output (wrong): EFBBBF0000010165C2BAC38B59

Expected output: 0000010165bacb59

**Comment by ushelp** [comment]
@ldlamarc 
Thanks for your feedback.

Because EasyQRCode default is to support text mode, some special characters in binary mode can cause encoding problem.
Now I release a new verison 3.8.0, it is support binary(hex) data mode.

- Change to binary mode:

 ```JS
 binary: true, // Use binary data mode
 ```

**Comment by ldlamarc** [comment]
With binary mode it works as expected for my use case. Thanks!

**Comment by ushelp** [comment]
Done.
