### ISSUE TITLE
Possible ES Module

### ISSUE THREAD

**Issue by Tea-Ice** [ushelp/EasyQRCodeJS#23]
I use the newest Angular with this, and it works fine, the only issue is that the new Ivy Compiler does not like CommonJS modules, and prefers ES modules for proper optimization.

**Comment by ushelp** [comment]
@Tea-Ice 
Thanks for your feedback.

There are two options to solve the warning.

**Option 1. Whitelist CommonJS dependency**

   add `allowedCommonJsDependencies` option to `angular.json`

	```JS
	{
	  
	  "projects": {
		"my-app": {
		  "projectType": "application",
		  ...
		  "architect": {
			"build": {
			  "builder": "@angular-devkit/build-angular:browser",
			  "options": {
				 ...
				"allowedCommonJsDependencies": [
				  "easyqrcodejs"
				],
			  }			
			  ...
	```
	
**Option 2. Making the path relative **

	```JS
	// import * as QRCode from 'easyqrcodejs';
	import * as QRCode from '../../node_modules/easyqrcodejs';
	```

Existing libraries cannot be migrated to ECMAScript module now. But we will consider releasing a separate`EasyQRCodeJS-es` version, so stay tuned.

**Comment by Tea-Ice** [comment]
@ushelp Any updates on the es module?
