### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by Jonsey4** [ushelp/EasyQRCodeJS#24]
In trying to add a logo to the QR code, any image added as a logo causes this error:

`Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

Here's the code:

```
var qrcode = new QRCode(document.getElementById("qrcode"), {
width: 200,
height: 200,
colorDark: "#282d36",
colorLight: "#ffffff",
correctLevel: QRCode.CorrectLevel.L, 
dotScale: 1,

logo: "any_image_path.png", 
logoWidth:100,
logoHeight: 100,
logoBackgroundTransparent:false
});
```

I've tried a number of things and seen no success.

**Comment by preservance717** [comment]
i also same problem. how do you solve this problem?

**Comment by ushelp** [comment]
Duplicate of #20

**Comment by ushelp** [comment]
@Jonsey4 
@preservance717 

Now please upgrade to latest version 4.3.1. 

Add `crossOrigin` option:

```JS
var options = {
   //...
     crossOrigin: 'anonymous', 
  //...
}
```

**Comment by ushelp** [comment]
https://github.com/ushelp/EasyQRCodeJS#q1-tainted-canvases-may-not-be-exported
