### ISSUE TITLE
TypeScript Issue

### ISSUE THREAD

**Issue by scottgeye** [ushelp/EasyQRCodeJS#26]
I just added easyqrcodejs to my TypeScript project, but I'm getting an error that the types can't be found when I try to import the module.

Code:

```
import * as QRCode from "easyqrcodejs";
```

Error:

```
Could not find a declaration file for module 'easyqrcodejs'. '/node_modules/easyqrcodejs/dist/easy.qrcode.min.js' implicitly has an 'any' type.
  Try `npm install @types/easyqrcodejs` if it exists or add a new declaration (.d.ts) file containing `declare module 'easyqrcodejs';
```

I tried doing the recommend install from the error, but there's no repo with that name.

**Comment by ushelp** [comment]
@scottgeye 
The EasyQRCodeJS is for browser. May be you can try:
https://github.com/ushelp/EasyQRCodeJS-NodeJS

**Comment by ushelp** [comment]
@scottgeye 

Please try create a `easy.qrcode.min.d.ts` file to `/node_modules/easyqrcodejs/dist/` folder.

paste the content below to the new file.

```JS
// Type definitions for easyqrcodejs-nodejs.js
// Project: [https://github.com/ushelp/EasyQRCodeJS-NodeJS-Premium/] 
// Definitions by: Ray <inthinkcolor@gmail.com> 

export = QRCode;

declare class QRCode {
    constructor(vOption: any);

    clear(saveOptions: any): any;

    makeCode(text: any): any;
    
    resize(width: any, height: any): any;

    static CorrectLevel: {
        H: number;
        L: number;
        M: number;
        Q: number;
    };
}
```

Try you code can run normaly now.

If it's work fine, please let me know, I will update the file to library. Thank you.

**Comment by scottgeye** [comment]
Using that exact code, I got this error from the ts compiler:

```This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.```

I already have allowSyntheticDefaultImports on, so not sure why that comes up.  If I change the import statement in my code that error goes away, but then there's an issue with definition of the constructor only taking one param.

Working import statement:

```
import QRCode from "easyqrcodejs";
```

Here's the types I ended up with that match the source.

```
export = QRCode

declare class QRCode {
    constructor(element: any, vOption: any);

    clear(): void;

    makeCode(text: string): void;
    
    resize(width: number, height: number): void;

    static CorrectLevel: {
        H: number;
        L: number;
        M: number;
        Q: number;
    };
}
```

Thanks

**Comment by ushelp** [comment]
can you provide a MVP project for me to test?

**Comment by scottgeye** [comment]
No problem.  Simple create react app wit typescript...

[qrtest.zip](https://github.com/ushelp/EasyQRCodeJS/files/5295933/qrtest.zip)

**Comment by ushelp** [comment]
The MVP project work fine for my testing.

- Compiled successfully!
![图片](https://user-images.githubusercontent.com/4082017/94538168-40b60800-0276-11eb-9864-6894f59768dc.png)

![图片](https://user-images.githubusercontent.com/4082017/94538145-38f66380-0276-11eb-96b7-b5d3d8908040.png)


Can you clean cache, reinstall dependencies and try again? please let me know if it works.

**Comment by scottgeye** [comment]
Works for me.

**Comment by ushelp** [comment]
Close since no comments.
