### ISSUE TITLE
QR Codes are not recognized by Android camera.

### ISSUE THREAD

**Issue by coding-challenge-android-temp** [ushelp/EasyQRCodeJS#29]
Hello. I am using the latest implementation of the library (4.0.0).
The library is great and everything works, except that it does not work on Android native cameras, nor standard QR apps like "QR Code Barcode Scanner" on google play. The QR-Code is generated correctly because I downloaded it and ran it through a qr image file scanner, it scans great. But I am not able to figure out why android scanners do not work. 

Here is an example of the code I am using, it's the standard implementation so I don't think I am screwing up here.

```

var options = {};
options["text"] = "TEST";

var qrcode = new QRCode(options);
  qrcode.toDataURL().then(data => {
    const im = data.split(",")[1];

    const img = Buffer.from(im, 'base64');

    res.writeHead(200, {
      'Content-Type': 'image/png',
      'Content-Length': img.length
    });
    return res.end(img);
  });
```

**Comment by ushelp** [comment]
@coding-challenge-android-temp could you provide a MVP project for my testing?

**Comment by coding-challenge-android-temp** [comment]
I will try to send you one tonight, if I can make some time. But it's not the implementation, I tried every combination possible and Android cameras do not scan them. I tried with every version from 1 to 40, logo, no logo, color, no color. There is no case.

Just use the example and try to scan them with the Android camera.

**Comment by coding-challenge-android-temp** [comment]
After trying broadly with all possible configurations, I made it work. I think that the quiet zone was the issue, with no quiet zone it did not scan.
It's a great and the best library I found for this problem, the only suggestion I would make is to either include the quiet zone in the example, or set it by default.
Thank you for your work.
