### ISSUE TITLE
Change data pattern style by passing svg image to use

### ISSUE THREAD

**Issue by anuj9196** [ushelp/EasyQRCodeJS#3]
- [x] Feature Request

Can I change the data pattern or eye pattern to different styles?

It will be helpful if data pattern and eye pattern can be changed by passing the svg code of the pattern.

Also, can I extract the pattern info of the QR code so that it could be regenerated simple by passing the pattern?

**Comment by ushelp** [comment]
@anuj9196 Good advice, I will consider it in the future.

**Comment by RGKrish183** [comment]
Is it possible to get the svg images instead of canvas images?

**Comment by ushelp** [comment]
@anuj9196 
https://github.com/ushelp/EasyQRCodeJS#easyqrcodejs-premium

@RGKrish183 
Does not support SVG, but you can use Canvas draw anything, except that it cannot be vector.
