### ISSUE TITLE
Low Quality Logo on Mobile

### ISSUE THREAD

**Issue by RYoder97** [ushelp/EasyQRCodeJS#30]
I have a 3600x3600 logo that I am trying to incorporate into a QR. For some reason it seems that whenever I try generating a QR with this HD logo on my mobile device (Galaxy S10e) it's blurrier than its Windows 10 PC counterpart. The QR itself seems blurrier too. I can only guess that high DPI displays have not been accounted for in the library? I've read that there are issues with HTML5 canvas and higher DPI displays. My laptop is a Lenovo Thinkpad x230 with a 1366x768 display, much lower res than my 2019 phone.

Any thoughts on this?

**Comment by ushelp** [comment]
@RYoder97 
Could you try SVG drawer?

**Comment by RYoder97** [comment]
I tired it and the result is better, however, SVG wouldn't work for my use case as what I'm developing requires canvas. Unless there is a way to save SVG to a Blob?

**Comment by RYoder97** [comment]
Scratch that, I definitely need canvas. I would first need to do SVG to Blob, then rasterize it back on another canvas. That takes a lot of resources, and can be sluggish.

**Comment by ushelp** [comment]
Maybe you can try to compress the image size to an appropriate ratio first, and then use canvas to draw.

**Comment by ushelp** [comment]
Closed without comment for a long time.
