### ISSUE TITLE
qrcode.resize() don't work 

### ISSUE THREAD

**Issue by amira-98** [ushelp/EasyQRCodeJS#32]
**Error : Cannot read property 'resize' of undefined** 
`
  var options_object = {
      text: props.location.state.link,
      colorLight: 'transparent',
      width: 150,
      height: 150,
      quietZone: 10,
      quietZoneColor: 'transparent',
      logo: onevcardlogo,
      logoWidth: 40, // width. default is automatic width
      logoHeight: 40,
    }

   var  codeobj = new EasyQRCode(qrcode.current, options_object)

  codeobj.resize(80, 80)
`

**Comment by ushelp** [comment]
@amira-98 
It's fine in my test. Have you tried to update to the latest version 4.0.0?
If still doesn't work, could you provide a MVP project for me to test.

**Comment by ushelp** [comment]
Closed due to no reply for a long time.
