### ISSUE TITLE
How to change eye form type (PO, PI) of QR code?

### ISSUE THREAD

**Issue by arman-mukatov** [ushelp/EasyQRCodeJS#35]

**Comment by ushelp** [comment]
The EasyQRCodeJS only support change eys form color. If you want change the shape, may be can try EasyQRCodeJS-Premium.
 https://github.com/ushelp/EasyQRCodeJS#easyqrcodejs-premium
If you need it, please contact me by email: <inthinkcolor@gmail.com>

**Comment by ushelp** [comment]
As libray and solution has been provided, closed.
