### ISSUE TITLE
Is it possible add the title in html?

### ISSUE THREAD

**Issue by antonioavelar** [ushelp/EasyQRCodeJS#36]
Just question... I think it would be awesome to have have the title + description, or add somehow a section above or bellow the qrcode with html. This way the devs would be able to fully customise the qrcode.

**Comment by ushelp** [comment]
Since QRCode drawing is based on Canvas API, it does not have the ability to render HTML code or CSS code.

**Comment by ushelp** [comment]
Closed due to no comments for a long time.
