### ISSUE TITLE
Please let logo supporting 'img.crossOrigin = "Anonymous"'

### ISSUE THREAD

**Issue by microkof** [ushelp/EasyQRCodeJS#37]
I want to set logo with crossOrigin.

Thank you!

Thank developer!

**Comment by ushelp** [comment]
Thanks for your advice.
Now we publish a new version 4.2.0 can support crossOrign option.

**Comment by microkof** [comment]
> Thanks for your advice.
> Now we publish a new version 4.2.0 can support crossOrign option.

Thank you, I tried it, logo is OK, but there is a bug in version 4.2.0:

```
easy.qrcode.min.js?6534:21 Uncaught ReferenceError: _htOption is not defined
```

**Comment by microkof** [comment]
> Thanks for your advice.
> Now we publish a new version 4.2.0 can support crossOrign option.

`if (_htOption.crossOrigin != null) {` should be `if (this._htOption.crossOrigin != null) {`

**Comment by ushelp** [comment]
The fixed version 4.2.1 released.
Thanks a lot for your prompt feedback.

**Comment by microkof** [comment]
> The fixed version 4.2.1 released.
> Thanks a lot for your prompt feedback.

There are some other errors.
`DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`
I suggest testing before releasing.
Thank you.

**Comment by microkof** [comment]
> The fixed version 4.2.1 released.
> Thanks a lot for your prompt feedback.

In fact, ver 4.2.1 does not support cross domain.

**Comment by ushelp** [comment]
Hey gus, have you configure the `crossOrigin:'anonymous'` option? In my test it's OK
![图片](https://user-images.githubusercontent.com/4082017/103283288-21fd1400-4a13-11eb-844a-7ed4ba679a71.png)


If still have error, could you please send me your MVP file, let me check it.

**Comment by microkof** [comment]
> Hey gus, have you configure the `crossOrigin:'anonymous'` option? In my test it's OK
> ![图片](https://user-images.githubusercontent.com/4082017/103283288-21fd1400-4a13-11eb-844a-7ed4ba679a71.png)
> 
> If still have error, could you please send me your MVP file, let me check it.

The function is available, thank you.
