### ISSUE TITLE
after remove logo quietZoneColor not working

### ISSUE THREAD

**Issue by ngankt2** [ushelp/EasyQRCodeJS#38]
i have no Logo.
quietZoneColor not working.
Same bug with: https://www.easyproject.cn/easyqrcodejs/tryit.html

**Comment by ushelp** [comment]
I'm not found the issue.

but I update the online libarary to latest.  Could you test again and let me know whether it fixed?

**Comment by ushelp** [comment]
Thanks for your feedback.

Now we release a new version 4.3.1 fixed the issue, please upgrade to the latest vesion.

Thanks agian.

**Comment by ushelp** [comment]
@ngankt2 
Thanks for your feedback.
Now we release a new version 4.3.1 fixed the issue, please upgrade to the latest vesion.
