### ISSUE TITLE
Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by jithinagiboson** [ushelp/EasyQRCodeJS#39]
![image](https://user-images.githubusercontent.com/53430451/103888905-8a32b080-510b-11eb-981e-fd9fff6a79a9.png)

try to export canvas todataURL()   or make a download link

current domain was localhost:8080

image was http://diui35v2plbz7.cloudfront.net/imagetargets/20190815185046.jpg

even though i put allow cross origin on s3 bucket stil its showing

**Comment by jithinagiboson** [comment]
i think internaly may be easy qrcode js may have a part were new Image() object is created which does not have a crossOrgin="annonymus" code missing

**Comment by ngankt2** [comment]
`function downloadAsPng(canvas, filename) {

        let lnk = document.createElement('a'), e;
        lnk.download = filename;
        lnk.href = canvas.toDataURL("image/png;base64");
        if (document.createEvent) {
            e = document.createEvent("MouseEvents");
            e.initMouseEvent("click", true, true, window,
                0, 0, 0, 0, 0, false, false, false,
                false, 0, null);
            lnk.dispatchEvent(e);
        } else if (lnk.fireEvent) {
            lnk.fireEvent("onclick");
        }
    }
`
`<button onclick="downloadAsPng(document.querySelector('#qrcode canvas'),'sita-app-qrcode.png')" type="button" class="btn btn-primary btn-sm">Download as PNG</button>`

You can see it at: [](https://sita.app/qrcode-generator)

**Comment by ngankt2** [comment]
Try this code: 
`function downloadAsPng(canvas, filename) {
        let lnk = document.createElement('a'), e;
        lnk.download = filename;
        lnk.href = canvas.toDataURL("image/png;base64");
        if (document.createEvent) {
            e = document.createEvent("MouseEvents");
            e.initMouseEvent("click", true, true, window,
                0, 0, 0, 0, 0, false, false, false,
                false, 0, null);
            lnk.dispatchEvent(e);
        } else if (lnk.fireEvent) {
            lnk.fireEvent("onclick");
        }
    }`

in html:
`<button onclick="downloadAsPng(document.querySelector('#qrcode canvas'),'sita-app-qrcode.png')" type="button" class="btn btn-primary btn-sm">Download as PNG</button>`

You can refer to online qr code generator: https://sita.app/qrcode-generator

**Comment by jithinagiboson** [comment]
> Try this code js:
> `function downloadAsPng(canvas, filename) { let lnk = document.createElement('a'), e; lnk.download = filename; lnk.href = canvas.toDataURL("image/png;base64"); if (document.createEvent) { e = document.createEvent("MouseEvents"); e.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null); lnk.dispatchEvent(e); } else if (lnk.fireEvent) { lnk.fireEvent("onclick"); } }`
> in html:
> `<button onclick="downloadAsPng(document.querySelector('#qrcode canvas'),'sita-app-qrcode.png')" type="button" class="btn btn-primary btn-sm">Download as PNG</button>`
> 
> You can refer to online qr code generator: https://sita.app/qrcode-generator

That is not the case here issue is cross orgin and have looked in to the qr code js code and found that cross orgin anonymus code was commented so .I have edited that like now i can be downloaded.I think i need to build the new minifided file my self

**Comment by ushelp** [comment]
@jithinagiboson 

Please upgrade to latest version 4.3.1. 

Add `crossOrigin` option:

```JS
var options = {
   //...
     crossOrigin: 'anonymous', 
  //...
}
```

**Comment by ushelp** [comment]
https://github.com/ushelp/EasyQRCodeJS#q1-tainted-canvases-may-not-be-exported

**Comment by ushelp** [comment]
Long time no feedback.

**Comment by jithinagiboson** [comment]
i have edited the code inside easy qr code js  to add cross origin
