### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by anuj9196** [ushelp/EasyQRCodeJS#4]
- [x] Feature Request

Is there support for `TypeScript` to use in **Angular 6+**?

**Comment by ushelp** [comment]
@anuj9196 Angular support JavaScript library yet, and EasyQRCodeJS also support Angular 6+, Vue.js, React.
Refer: https://github.com/ushelp/EasyQRCodeJS#angular-support

**Comment by anuj9196** [comment]
I got this error while running
```
ng add easyqrcodejs
```
```
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

**Comment by ushelp** [comment]
@anuj9196 Don't worry, it's doesn't matter.

You also can use  `npm install easyqrcodejs`  to get the same feture.

**Comment by ushelp** [comment]
@anuj9196  Don't worry, it's doesn't matter.

You can also use `npm install easyqrcodejs` to get the same feature.
