### ISSUE TITLE
Rounded Position indicators

### ISSUE THREAD

**Issue by b4oz** [ushelp/EasyQRCodeJS#40]
Is there a way to customise the Position indicators to display with rounded corners, dotted or solid border and internal marker being a circle,star,square etc?

**Comment by ushelp** [comment]
@b4oz 
Do you mean this(EasyQRCodeJS-Premium)?

![EasyQRCodeJS-Premium](https://raw.githubusercontent.com/ushelp/EasyQRCodeJS/master/doc/images/demo-premium.png)

**Comment by b4oz** [comment]
Never knew there was a Premium! Where can I find the details?

**Comment by ushelp** [comment]
Please contact we by this email get the dtails.
 <inthinkcolor@gmail.com>
