### ISSUE TITLE
Rougue console.log

### ISSUE THREAD

**Issue by Tea-Ice** [ushelp/EasyQRCodeJS#42]
Ever since I updated to 4.3.1 I get a console log from the package every time a QR-code is generated. Not a huge problem, just annoying. Example: `rgba(0, 0, 0, 0) easy.qrcode.min.js:21:6401`

**Comment by ushelp** [comment]
Sorry to trouble you and thanks for your feedback.
Annoying console log has been removed. Please upgrade to `4.3.2`.

**Comment by Tea-Ice** [comment]
Issue fixed. Thanks for the quick resolution!
