### ISSUE TITLE
Download of QRCode does not include Logo or Background image

### ISSUE THREAD

**Issue by b4oz** [ushelp/EasyQRCodeJS#43]
When dynamically setting the background image or logo of the QRCode and using the below code to download the resulting image, no background or logo is saved in the image.

`  
  $('#qrcode').attr('crossOrigin', 'anonymous');

  $('#qrcode').attr('href', document.querySelector('canvas').toDataURL('image/png'));

  $('#qrcode').attr('download', 'testdownload');
`

When using option.backgroundImage the downloaded image is blank, when using options.logo the downloaded image does not contain the logo.

Using Chrome or Firefox the "Right Click save as" will download the correct image, this does not work on Safari.

**Comment by ushelp** [comment]
If you want get the qrcode image file, Maybe you can try use [EasyQRCodeJS-NodeJS]( https://github.com/ushelp/EasyQRCodeJS-NodeJS) to generate qrcode on the server side.

**Comment by ushelp** [comment]
The download function has been released, please update your library to 4.5.0 or above.

Please refer to: 
https://github.com/ushelp/EasyQRCodeJS#download-the-qrcode-image-in-the-browser
