### ISSUE TITLE
Does this library support the сyrillic?

### ISSUE THREAD

**Issue by grambg** [ushelp/EasyQRCodeJS#47]
I tried to generate a code with сyrillic and it is generated incorrectly. What am I doing wrong?

![Без названия (6)](https://user-images.githubusercontent.com/273784/115715484-d800bb00-a380-11eb-9fdf-90fea980ccf5.png)

**Comment by ushelp** [comment]
Could you provide an mvp project for me to test?

**Comment by ushelp** [comment]
closed because long time no response.
