### ISSUE TITLE
CORS error when fetching cached image for logo

### ISSUE THREAD

**Issue by saturnonearth** [ushelp/EasyQRCodeJS#48]
If the code requests the logo image from cache, it fails from a lack of CORS headers.

`Blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

(fails)
![image](https://user-images.githubusercontent.com/12503538/115790447-b6a9ca00-a394-11eb-87f9-786257ac063f.png)

(succeeds)
![image](https://user-images.githubusercontent.com/12503538/115790515-d5a85c00-a394-11eb-83a9-70f12520ec65.png)

Could this be caused from the recent change that uses the cached version of the image?

**Comment by ushelp** [comment]
Hey, @saturnonearth 

There is no problem after the test, you can try the following code to check first:
(Please make sure you can access the logo image [https://raw.githubusercontent.com/ushelp/EasyQRCodeJS/master/demo/logo-transparent.png](https://raw.githubusercontent.com/ushelp/EasyQRCodeJS/master/demo/logo-transparent.png))

```JS
var config = {
        text: "easyproject.cn/donation",

        width: 200,
        height: 200,
        // quietZone: 10,
        // quietZoneColor:'#ff0000',
        colorDark: "#038EC4",
        colorLight: "#F1F1F1",

        correctLevel: QRCode.CorrectLevel.H, // L, M, Q, H

        crossOrigin: 'anonymous',

        logo: 'https://raw.githubusercontent.com/ushelp/EasyQRCodeJS/master/demo/logo-transparent.png',

        logoBackgroundTransparent: true
    }
```

**Comment by saturnonearth** [comment]
When loading my own, image, I have CORS set to global *, and am able to view the image fine, but will get this error, only from EasyQR, 
![image](https://user-images.githubusercontent.com/12503538/116121211-64b3bd80-a68e-11eb-8abe-daaf0e9cd847.png)

**Comment by ushelp** [comment]
My Test case for your references:

## Test case 1 - Have CORS settings on the server side
- Server side (Express-NodeJS)
```JS
const cors = require('cors')
...
app.use(cors()) // CORS
```

- Front end
```JS
crossOrigin: 'anonymous', 
```

Test results:  **passed**

## Test case 2 - No CORS settings on the server side
- Server side (Express-NodeJS)
```JS
//const cors = require('cors')
...
//app.use(cors()) // CORS
```

- Front end
```JS
//crossOrigin: 'anonymous', 
```
Test results:  **passed**

**Comment by saturnonearth** [comment]
Hm I am still experiencing this error on the client side. It happens quite often and breaks the entire QR code generation.

**Comment by ushelp** [comment]
Could you share me the qrcode configuration for testing?  Especially your image url.
