### ISSUE TITLE
How we can add a frame outside the QRcode and add text at bottom?

### ISSUE THREAD

**Issue by futuretech123** [ushelp/EasyQRCodeJS#5]
I have found a couple of feature missing in library documentation:

1. How we can add a frame to QRcode?
2. How we can add text at bottom of QR code?
3. How we can round the Logo image?

Thanks

**Comment by ushelp** [comment]
Sorry, no such support is provided now, these are additional features, it's recommended u can customize it for youself.
I will consider it.
