### ISSUE TITLE
LogoBackgroundTransparency not working

### ISSUE THREAD

**Issue by saturnonearth** [ushelp/EasyQRCodeJS#51]
Here is my setup:

![image](https://user-images.githubusercontent.com/12503538/117380423-a66f1000-aea7-11eb-9d0c-9bd737a6470e.png)

And for some reason it still shows a white background:
![image](https://user-images.githubusercontent.com/12503538/117380579-01086c00-aea8-11eb-9963-3676b7256184.png)

**Comment by ngankt2** [comment]
[](https://sita.app/qrcode-generator)

it still works fine.
Can you send your photos for everyone to see?

**Comment by saturnonearth** [comment]
Yea it's odd, I have no special settings, and I tried in your link, and even in the projects example, and it is working fine. Something is causing it to add a white background.

**Comment by ngankt2** [comment]
https://github.com/ushelp/EasyQRCodeJS/issues/1

You try to refer to this document.
hope it helps

**Comment by saturnonearth** [comment]
Yea that property value is no longer relavant.

**Comment by ushelp** [comment]
@ngankt2 
Please check if your image has a transparent background.

You can try to modify the code in the demo.html to verify. 

![图片](https://user-images.githubusercontent.com/4082017/118125968-3f62d580-b42a-11eb-8481-40267a4e5c4d.png)


```JS
logoBackgroundColor: '#ffffff', // Logo backgroud color, Invalid when `logBgTransparent` is true; default is '#ffffff'
logoBackgroundTransparent: false, // Whether use transparent image, default is false
```

**Comment by ushelp** [comment]
@saturnonearth 
Will send you the new Premium version package.
