### ISSUE TITLE
Blank QR code generated

### ISSUE THREAD

**Issue by gqqnbig** [ushelp/EasyQRCodeJS#54]
```
a=new QRCode($0, {text:'https://www.freedesktop.org/software/systemd/man/systemd.service.html', 'height':20, 'width':20});
```
$0 refers to the highlighted element in Developer Tool.

The code does not generate a visible QR code. It does generate a `canvas` element with width and height 0.

I believe EasyQRCodeJS fails to generate because the size is too small and the text is too long.

Is there a way I can tell that if the generation is successful?

**Comment by ushelp** [comment]
Thanks for your advice.

We have released a new version to fix this issue, please upgrade to the latest version 4.4.1.

**Comment by gqqnbig** [comment]
Thanks for the Quick Response.

I confirm the aforementioned code works with version 4.4.1, which generates a QR code of size 49.

I'm fine with an altered size for a guaranteed generation. Though, someone may want to a test that if certain size can hold certain amount of text. Anyway, you can save it for later.

**Comment by ushelp** [comment]
In fact, we will keep the minimum size of the block as 1*1 pixels, the smallest QRCode should be 21*21(QR Code symbol version 1)
![图片](https://user-images.githubusercontent.com/4082017/119773743-ad5fd000-bef3-11eb-8b97-63e4b080be7b.png)
