### ISSUE TITLE
Looks excellent but buggy.

### ISSUE THREAD

**Issue by GordonData** [ushelp/EasyQRCodeJS#56]
scanned result does not match text ( aka, qrcode is not correct. )

require(["easy.qrcode.js"], function(QRCode){
  var options = {
    text: "https://chinese.gordondata.com.au/index.html?Article=九月九日忆山东兄弟（盛唐·王维）&HZField=Simplified&PYField=PinYin", 
    correctLevel : QRCode.CorrectLevel.H,
  }
  new QRCode(document.getElementById("output"), options);
});

**Comment by ushelp** [comment]
Based on my test, this seems to be no problem, could you tell me where is incorrect?

please try to scan and check the results.

![图片](https://user-images.githubusercontent.com/4082017/120667071-b89c9800-c4bf-11eb-882e-978d743c668c.png)

Test devices: iPhone Camera, QRefine APP, WeChat APP...

**Comment by ushelp** [comment]
Closed without comments for a long time.
