### ISSUE TITLE
Small Bug - Out of bounds error - A single character change needed

### ISSUE THREAD

**Issue by scglenn** [ushelp/EasyQRCodeJS#57]
File: https://github.com/ushelp/EasyQRCodeJS/blob/master/src/easy.qrcode.js
Line: 1875
Code: `for (var i = 0, len = QRCodeLimitLength.length; i <= len; i++) {`

Problem: The variable 'i' increments to be equal to 'len' in the case where too much data is being stored in the QR code. This causes an out of bound error in the for loop.

Solution: Modify the for loop to `for (var i = 0, len = QRCodeLimitLength.length; i < len; i++) {` by removing the '=' character.
This allows the `throw new Error("Too long data");` logic to execute.

**Comment by ushelp** [comment]
We have released a new version to fix this issue, please upgrade to the latest version 4.4.3.
Thanks a lot.

**Comment by scglenn** [comment]
Nice, glad I could help.
