### ISSUE TITLE
Can we use "crossorigin" attribute?

### ISSUE THREAD

**Issue by pouu69** [ushelp/EasyQRCodeJS#6]
When using canvas / image, we need to  `crossorigin = "anonymous"` attribute.
Why did you comment it out?
Can't use it?
I need the dataURI specified in the generated canvas.

**Comment by ushelp** [comment]
@pouu69 
If add `crossorigin = "anonymous"` attribute, means the Server must set CROS header  'Access-Control-Allow-Origin' to allow, otherwise you cannot access the pictures.
I think it's redundant. can you give me your scene or reason?
