### ISSUE TITLE
How to get base64 in browser?

### ISSUE THREAD

**Issue by ibalaji777** [ushelp/EasyQRCodeJS#60]
I used qrcode js to get base64 below syntax
const qrcode = new QRCode(document.createElement('div'), {
	text: "http://jindo.dev.naver.com/collie",
	width: 128,
	height: 128,
	colorDark : "#000000",
	colorLight : "#ffffff",
	correctLevel : QRCode.CorrectLevel.H
});
qrcode._oDrawing._elImage.onload = ev => { 
    console.log(ev.target.src);
}
But not working in easyqrcode 

How to get base64 url?

**Comment by ushelp** [comment]
`onRenderingEnd(qrCodeOptions, dataURL)` 

Callback function when the rendering ends. dataURL parameter is the base64 data(canvas drawer) or SVG serialized text(svg drawer) of QRCode image(if not support canvas return null).

**Comment by ibalaji777** [comment]
Awesome ,thank you for your library @ushelp
