### ISSUE TITLE
How to get the dataUrl

### ISSUE THREAD

**Issue by afxtechnologies** [ushelp/EasyQRCodeJS#62]
Hi, good day ...

easyQRCodeJS is a good utility. may i know if i can access to the data/element dataUrl which i can see it in o_Drawing element.
I need to use the value.

Thank you for a great tool.

**Comment by ushelp** [comment]
Duplicate of #60 
https://github.com/ushelp/EasyQRCodeJS/issues/60#issuecomment-872012671

**Comment by afxtechnologies** [comment]
Excellent! thank you ... managed to get it work 

    var qrcode = new QRCode(document.getElementById("qrCode"), {
      text: "https://github.com/ushelp/EasyQRCodeJS",
      width: 100,
      height: 100,
      onRenderingEnd: (qrCodeOptions, dataURL)=> {
                        this.imgSrc = dataURL;
                      }
    });

-ionic3-

**Comment by L1cardo** [comment]
@ushelp 请问 `QRCode(document.getElementById("qrCode"), options)`必须要有第一个参数吗？
我想先 ` var code = QRCode() `，不要先展示到到html，然后后面再` appendChild(qrcode) `，请问可以实现吗？

原因是上面所说的获取`DataURL`是先展示到html，然后才能拿到`DataURL`， 而我想先拿到，因为我想展示一个img，而不是canvas，所以我的做法是先展示 然后`clear `， 然后转成img，再展示， 感觉不太优雅

```javascript
var qrcode = new QRCode(document.getElementById("qrcode"), {
  text: "https://github.com/ushelp/EasyQRCodeJS",
  width: 180,
  height: 180,
  logo: "logo.jpg",
  onRenderingEnd: (qrCodeOptions, dataURL)=> {
  qrcode.clear()
  var img = new Image()
  img.src = dataURL
  document.getElementById("qrcode").appendChild(img)
                  }
})
```
