### ISSUE TITLE
width and height are not accurate

### ISSUE THREAD

**Issue by now915** [ushelp/EasyQRCodeJS#63]
I set qrcode options { width: 430, heigth: 430 }, and generate it. But the canvas's width  and height 
are 444px in HTML, so do the other width and height which setted in options.

How  can I generate a accurate qrcode witdh  easyqrcodejs...

I use vue and  the version of easyqrcodejs is 4.4.3

**Comment by ushelp** [comment]
Duplicate of #18 #61
