### ISSUE TITLE
how to avoid multiple times append qrcode?

### ISSUE THREAD

**Issue by ibalaji777** [ushelp/EasyQRCodeJS#66]
qrcode renders multiple times

**Comment by ivansnek** [comment]
@ibalaji777 In case you're using it with React, and creating it inside a `componentWillReceiveProps` or a `useEffect` hook with
`new QRCode(element, options)`
1. Make sure you're saving the new instance `myInstance = new QRCode(element, options)`
2. On component update make sure to first call `myInstace.clear()`

**Comment by ushelp** [comment]
Ivansnek was right: clear and regeneration.

Closed since no comments long time.

**Comment by Austin-dv-Evans** [comment]
@ivansnek Could you please elaborate on your solution? I am running into this same situation and I am currently iterating over nodes and removing them, and your way seems much better. I am creating inside a useEffect hook. would I need to save the variable as a state? Where would I call clear, I don't want to clear the newly created my_instance.

**Comment by ivansnek** [comment]
> @ivansnek Could you please elaborate on your solution? I am running into this same situation and I am currently iterating over nodes and removing them, and your way seems much better. I am creating inside a useEffect hook. would I need to save the variable as a state? Where would I call clear, I don't want to clear the newly created my_instance.

Hi @Austin-dv-Evans here is the implementation example I had, I hope it helps, btw I'm using typescript
```
import { FC, useEffect, useRef, useState } from 'react'
// Optional if you want to use a icon in the center of the QRCode
import Badge from 'static/badge.png'
import QRCode from 'easyqrcodejs'

interface QRCodeProps {
  value: string,
  size?: number,
  className?: string,
  style?: object,
  darkMode?: boolean,
  useLogo?: boolean,
}
const QRCodeComponent: FC<QRCodeProps> = ({
  value = 'some-default-value',
  size = 300,
  className = '',
  style = {},
  darkMode = true,
  useLogo = true,
}) => {
  const [qrCode, setQRCode] = useState()
  const qrcodeRef = useRef()
  useEffect(function onUpdate() {
    if (qrCode) {
      qrCode.clear()
    }
    let options = {
      dotScale: 0.7,
      dotScaleTiming: 0.7,
      quietZone: 30,
      text: value,
      width: size,
      height: size,
      colorDark : darkMode ? '#ffffff' : '#000000',
      colorLight : darkMode ? '#000000' : '#ffffff',
    }
    if (useLogo) {
      options = {
        ...options,
        logo: Badge,
        logoBackgroundColor: darkMode ? '#000000' : '#ffffff',
        logoWidth: Math.abs(size / 4),
        logoHeight: Math.abs(size / 4),
      }
    }
    const qr = new QRCode(qrcodeRef.current, options);
    setQRCode(qr)
  }, [value, size, darkMode, useLogo])

  return (
    <div
      ref={qrcodeRef}
      className={className}
      style={style}
    />
  )
}

QRCodeComponent.displayName = 'QRCodeComponent';

export default QRCodeComponent
```
