### ISSUE TITLE
Not recognized MeCard QR Code generated from non-ASCII characters as UTF-8 with BOM

### ISSUE THREAD

**Issue by omegastripes** [ushelp/EasyQRCodeJS#67]
BOM character `EF BB BF` [added at the beginning](https://github.com/ushelp/EasyQRCodeJS/blob/361e16645ae1bda2d1cb2dd017e8e16b21f3d232/src/easy.qrcode.js#L84-L88) prevents a scanning application from recognizing QR Code as MeCard. Recognized as plain text (no "Add contact" button appears). Need an option to control whether to add BOM character or not.

The simplest string for testing purposes might be `MECARD:N:Á;`.

Tested on [QR Droid Private](https://play.google.com/store/apps/details?id=la.droid.qr.priva&hl=en&gl=US).

**Comment by ushelp** [comment]
@omegastripes  Thanks for your feedback.
Now we use **UFT-8 without BOM** as the default setting. 
You can upgrade to the latest version `4.4.1`, no code need to change from your side.


And we provide the `utf8WithoutBOM` option to set whether to use BOM.
```JS
  // =====  UTF-8 without BOM
  /*
  utf8WithoutBOM: true
  */      
```
