### ISSUE TITLE
logo update support?

### ISSUE THREAD

**Issue by CmmmmmmLau** [ushelp/EasyQRCodeJS#68]
hi, 

I tried to generation the QRcode with the different logo but only used one `options_object` variable.
here is my code.
```
    <script>
        var codechose = "canvas-all";
        var logo = "all.jpg";

        var options_object = {
            width: 300,
            height: 300,
            colorDark : "#000000",
            colorLight : "#ffffff",
            logo: logo,
            correctLevel : QRCode.CorrectLevel.Q, // L, M, Q, H
            onRenderingEnd: (qrCodeOptions, dataURL)=> {
                var img = new Image()
                img.src = dataURL
                document.getElementById(codechose).appendChild(img);
            }
        };
        var qrcode = new QRCode(document.getElementById("canvas"), options_object);
    </script>
```
and then I uesd `if` to change the target container and logo base on UA.
```
    <script>
        if(navigator.userAgent.match(/Alipay/i)) {
            window.location.href = url.alipay;
        } else if(navigator.userAgent.match(/MicroMessenger\//i)) {
            document.getElementById("code-wechat").style.display = "block";
            qrcode.makeCode(url.wechat);
            codechose = "canvas-wechat";
            logo = "wechat.jpg"
        } else if(navigator.userAgent.match(/QQ\//i)) {
        } else {
            document.getElementById("code").style.display = "block";
            qrcode.makeCode(window.location.href);
        }
    </script>
```
The target container changeing is working well, however the logo didn't changed.
Is there have another method similar with `makeCode()` but use to change the logo instead of text?

Or maybe a new method such as `optionUpdate()` could allow to change whole options?
Silmar with the `update()` method of this project.-https://github.com/kozakdenys/qr-code-styling

Thanks

**Comment by ushelp** [comment]
We designed `makeCode` only can change the QRCode text, does not include style changes. 

If you want to change the QRCode Style, you can regerenate the QRCode.

**Comment by CmmmmmmLau** [comment]
> We designed `makeCode` only can change the QRCode text, does not include style changes.
> 
> If you want to change the QRCode Style, you can regerenate the QRCode.

Have any method or way can simply regerenate the QRCode?

**Comment by ushelp** [comment]
1. Clear/remove the QRCode DOM element  
2. Modify your QRCode options 
3. New QRCode object again

**Comment by CmmmmmmLau** [comment]
> 1. Clear/remove the QRCode DOM element
> 2. Modify your QRCode options
> 3. New QRCode object again

It work. Thank you.
