### ISSUE TITLE
Parent container is not preserved when rendering

### ISSUE THREAD

**Issue by yannpiot** [ushelp/EasyQRCodeJS#69]
Using Angular, I generate a QR Code instance by passing an `ElementRef`, like this:

```
this.QRCode = new QRCode(someElementRef, options);
```

This works fine. However, it appears that the parent DOM element (`someElementRef`) is destroyed in the process of creating the code. And re-creating a QR code instance using the same line of code will trigger an exception (`someElementRef` is undefined).

As an alternative, I know I could re-generate the code `this.QRCode.MakeCode("new value")`, however in my particular case, the QR Code instance itself (`this.QRCode`) has also been disposed and so there isn't a way for me to create a new QR code again.

**Comment by ushelp** [comment]
Could you provide a MVP for my testing? because I think we have not remove the parent container `someElementRef`.

**Comment by ushelp** [comment]
Closed due to no feedback for a long time.
