### ISSUE TITLE
Certain options not working or have no function.

### ISSUE THREAD

**Issue by cyoung502** [ushelp/EasyQRCodeJS#7]
I setup a project to test all the options available in EasyQRCodeJS and I ran into a few issues.  The options are named correctly, and set using valid parameters however they have no effect on the generated QR code.

### Options

- PO(string)
- PI(string
- timing(string)
- titleTop(number)
- subTitleTop(number)

**PO**, **PI,** and **timing** should globally set the color of their respective elements, they don't.  You can still set the colors using **PO_TL**, **PO_TR**, **PO_BL**, **PI_TL**, **PI_TR**, **PI_BL**, **timing_H**, and **timing_V**.
 
**titleTop** and **subTitleTop** should set the position of their respective elements, they don't.  There is no other way to set the position of these title elements

Everything else is working great I really appreciate this project. Thank you for your hard work!

**Comment by ushelp** [comment]
@cyoung502 
1. PO, PI, and timing  are the default settings when you don't want to set   PO_TL, PO_TR, PO_BL, PI_TL, PI_TR, PI_BL, timing_H, and timing_V individually.  
2. Thanks for your feedback, I release a new version 3.5.2 to fixed this issue.
