### ISSUE TITLE
Data-id attribute for canvas

### ISSUE THREAD

**Issue by melikyan-a** [ushelp/EasyQRCodeJS#70]
Is it possible to add data-id attribute as option?

**Comment by ushelp** [comment]
Sorry, the feature is currently not supported. 

May I know what problem it can solve for you?

**Comment by melikyan-a** [comment]
@ushelp thanks for the answer

In my case, I need to remove and add new QRCode dynamically on a page, need know which QRCode must delete by click on some button with the same id.

**Comment by ushelp** [comment]
The QRCode in your DOM object. I think you can use the Dom id to clear or add new QRCode.

**Comment by melikyan-a** [comment]
@ushelp Yes, I did it, but it would be better not create unnecessary elements.

Thanks!

**Comment by ushelp** [comment]
Closed as we do not plan to support this feature.
