### ISSUE TITLE
The logo in QR code looks blur

### ISSUE THREAD

**Issue by n5ken** [ushelp/EasyQRCodeJS#71]
I guess this may caused by the canvas setting, refer to the link below, we can turn off the smoothing option.

https://stackoverflow.com/questions/18547042/resizing-a-canvas-image-without-blurring-it

**Comment by n5ken** [comment]
Using `drawer: 'svg'` looks great

**Comment by ushelp** [comment]
@n5ken Thanks for your research.

We pulish a new version `4.4.9` to set the quality of image smoothing. But it's currently only supported in Chrome when your image is zoomed out.

The quality of image smoothing is a big topic, need more support from vendors and underlying implementations. We will continue to pay attention and improve it.

**Comment by ushelp** [comment]
Closed due to no feedback for a long time.
