### ISSUE TITLE
crossOrigin: null

### ISSUE THREAD

**Issue by ritunjaykumar** [ushelp/EasyQRCodeJS#73]
crossOrigin: null, // String which specifies the CORS setting to use when retrieving the image. null means that the crossOrigin attribute is not set.

how to use this

**Comment by ushelp** [comment]
@ritunjaykumar  

Please refere: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin' to set what value you need.

**Comment by ushelp** [comment]
Resolved
