### ISSUE TITLE
How to breakline a long text in "Title"

### ISSUE THREAD

**Issue by doraemonxxx** [ushelp/EasyQRCodeJS#74]
I've been using easyqrcodejs for my project and it helps me a lot. Thank you

**Question**
is there an option on how to break the word if it's long? I already read the docs in npm but seems like I cant see it.

Thank you

**Comment by ushelp** [comment]
Sorry, word wrapping of long text is currently not supported, you can decrease the text font size, or use subTitle for text display of **up to two lines**.

If you have special needs, you can consider purchasing the premium version for custom drawing.
