### ISSUE TITLE
The logo flashes when code changing

### ISSUE THREAD

**Issue by LiYanLance** [ushelp/EasyQRCodeJS#75]
Hi, thanks for the amazing work.

I currently met an issue when trying to use [`makeCode(text)`](https://github.com/ushelp/EasyQRCodeJS#method) method on QR code with a logo, the logo flashes as the code changing. Check the link  to [produce it in codesandbox](https://codesandbox.io/s/easy-qr-code-with-logo-forked-i1xl21).

Could you help take a look?

**Comment by ushelp** [comment]
Yes, you are right. 

Actually `makeCode` function need to clear the canvas content and repaint, and drawing the logo image is asynchronous.

If you don't want to see flashes while drawing,  you can to control and display after rendering is complete. The `onRenderingEnd(qrCodeOptions, dataURL)` function can let you know that the drawing is done.

**Comment by LiYanLance** [comment]
Hey @ushelp , thanks for the response.

>display after rendering is complete

sounds not an option to me, since I was trying to use it in fountain code, which makes it never stops rendering new content.

I guess I need to either drop the logo, or use something else. 😔

**Comment by ushelp** [comment]
You can assess whether this will actually affect your rendering(Stop your rendering). 

It just let every QRCode image shows at the right time, refreshes/display your qrcode when it's completely done. No block for your fountain code.

**Comment by ushelp** [comment]
Closed, no comments for a long time.
