### ISSUE TITLE
It is impossible to modify options after QRCode creation

### ISSUE THREAD

**Issue by yeraycaballero** [ushelp/EasyQRCodeJS#79]
Hi @ushelp , Thanks for this library. I was wondering if you would consider to expose some methods in the api to allow modifications in the QRcode after creation. At the moment we can only change the text and the size using makeCode and resize methods, but I can't see anything to change for example the darkColor or the lightColor

I working on a no-code designer tool and I would like be able to modify the QRCode component settings like darkColor, lightColor, ... etc.
Regards

**Comment by ushelp** [comment]
Actaully, any option change requires redrawing the image, Not really modify after drawing.

You can modify the QRCode options, then regenreate the QRCode.

**Comment by ushelp** [comment]
Closed, no comments for a long time.
