### ISSUE TITLE
Async await on onRenderingEnd

### ISSUE THREAD

**Issue by Zombieteer** [ushelp/EasyQRCodeJS#81]
How can we apply await on onRenderingEnd?
since onRenderingEnd returns after the remaining code has returned

<img width="581" alt="image" src="https://user-images.githubusercontent.com/48326987/189235999-d9d4ff28-702e-4926-a432-c4c088637f2b.png">

**Comment by ushelp** [comment]
Please use Promise object to encapsulate it yourself.

**Comment by Zombieteer** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/48326987/189295571-2833bba2-625e-41af-9852-2f7e09914ce7.png">
thanks, it worked that way.
