### ISSUE TITLE
Changing cell styles

### ISSUE THREAD

**Issue by huffmanks** [ushelp/EasyQRCodeJS#82]
Is there a way a feature could be added to be able to change the style of the cells, i.e. plain, round, dot like this [example](https://qr-creator.com/url.php)? 

<img width="1174" alt="Screen Shot 2022-09-21 at 9 00 43 AM" src="https://user-images.githubusercontent.com/55319887/191510579-57f1d8f6-3595-4340-a9ef-2bf7c0fa65f6.png">

**Comment by ushelp** [comment]
Sorry, the free version can not change styels.

If you have special needs, you can consider purchasing the premium version for custom drawing.
https://github.com/ushelp/EasyQRCodeJS#easyqrcodejs-premium

**Comment by sinyang** [comment]
How can we test out the premium version? And where can we find pricing info?

**Comment by ushelp** [comment]
@sinyang 
If you need it, please contact me by email: [inthinkcolor@gmail.com](mailto:inthinkcolor@gmail.com)
