### ISSUE TITLE
Is there away to download

### ISSUE THREAD

**Issue by fireole** [ushelp/EasyQRCodeJS#84]
Is there a way to download the rendered canvas through a button click?

**Comment by verce190** [comment]
This is the hack I've used: 
    
var canvas = <any>document.getElementsByTagName("canvas")[0]; <---- this is the tricky part. You will need to find the canvas element. The devs of this script will be good to add an Id to the canvas (the one we specify in the div. That will help us download by id).
    
    canvas.toBlob((blob) => {
        let link = <any>document.createElement('a');
        link.download = 'qr.png';

        let reader = new FileReader();
        reader.readAsDataURL(blob);
        reader.onload = () => {
          link.href = reader.result;
          link.click();
        };   
    }, "image/png");
