### ISSUE TITLE
Rounded Eyes

### ISSUE THREAD

**Issue by rexarvind** [ushelp/EasyQRCodeJS#85]
How can I create rounded or circular QR Codes Eyes?

**Comment by ushelp** [comment]
If you want change the shape, may be can try EasyQRCodeJS-Premium.
https://github.com/ushelp/EasyQRCodeJS#easyqrcodejs-premium
If you need it, please contact me by email: [inthinkcolor@gmail.com](mailto:inthinkcolor@gmail.com)
