### ISSUE TITLE
Not working in firefox

### ISSUE THREAD

**Issue by JonnyTech** [ushelp/EasyQRCodeJS#90]
Tested Firefox 126.0 Linux amd64

Easy test, try with https://www.easyproject.cn/easyqrcodejs/tryit.html

Chromium based browsers produce QR code but Firefox just a transparent square.

No errors logged in console.

**Comment by trasherdk** [comment]
Win 8.1 :smiley: 
![image](https://github.com/ushelp/EasyQRCodeJS/assets/5003891/3dfad919-1b49-4241-ae47-868904bae977)

**Comment by DDtMM** [comment]
Worked fine 👌 on Firefox for Android version 128.0.3.

**Comment by JonnyTech** [comment]
Working on recent Firefox Linux builds, thanks → closing
